// Generated by CoffeeScript 1.7.1
(function() {
  var engine, test_input, test_output;

  engine = require('../lib/engine');

  test_input = function(name, start_delay, shutdown_delay) {
    return {
      start: function(emit, cb) {
        return setTimeout(function() {
          console.log("started " + name);
          return cb();
        }, start_delay * 1000);
      },
      shutdown: function(cb) {
        return setTimeout(function() {
          console.log("shutdown " + name);
          return cb();
        }, shutdown_delay * 1000);
      }
    };
  };

  test_output = function(name, start_delay, shutdown_delay) {
    return {
      start: function(cb) {
        return setTimeout(function() {
          console.log("started " + name);
          return cb();
        }, start_delay * 1000);
      },
      shutdown: function(cb) {
        return setTimeout(function() {
          console.log("shutdown " + name);
          return cb();
        }, shutdown_delay * 1000);
      }
    };
  };

  console.log("aaaaaaaaaaaaaa");

  engine.start(function(err) {
    return console.log("engine started " + err);
  });

  engine.add_input(test_input("input1", 1, 1), null, function(err, ii) {
    return console.log(ii);
  });

  engine.add_input(test_input("input2", 1, 1));

}).call(this);
