// Generated by CoffeeScript 1.7.1
(function() {
  var Tail, args, assert, count, file, t, total;

  Tail = require('../tail').Tail;

  assert = require('assert');

  if (!module.parent) {
    args = process.argv.slice(2);
    file = args[0];
    total = parseInt(args[1]);
    t = new Tail(file);
    count = 0;
    t.on('line', function(line) {
      var line_num, memory;
      console.log(line);
      count += 1;
      line_num = parseInt(line.split(":")[0]);
      assert.equal(line_num, count, "line received sequence is wrong");
      if (count === total) {
        memory = t.unwatch();
        console.log("success!");
        return console.log(memory);
      }
    });
  }

}).call(this);
