// Generated by CoffeeScript 1.7.1
(function() {
  var run, supervisor, supervisord;

  supervisor = require('../_lib/supervisor');

  run = function() {
    setInterval(function() {
      return console.log("running");
    }, 1000);
    return supervisor.checkHeartbeat(3000);
  };

  supervisord = function() {
    var args, script, sup;
    console.log(process.pid);
    script = process.argv[1];
    args = process.argv.slice(2);
    sup = supervisor.Supervisor(script, args, 3000);
    return sup.run(function(err) {
      return console.log(err);
    });
  };

  if (!process.env.__supervisor_child) {
    supervisord();
  } else {
    run();
  }

}).call(this);
