// Generated by CoffeeScript 1.7.1
daemon = require('./_lib/daemonize')
fs = require('fs')

out = './out.log'
err = './err.log'
d = daemon({
  script : './test.js',
  args: [],
  pidFile: './test.pid',
  outFile: out,
  errFile: err,
  startTimeout: 3000,
  stopTimeout: 3000
})

if(process.argv[2] == 'start'){
  d.start(function  (err) {
    console.log(err)
    process.exit()
  })
}else if(process.argv[2] == 'stop'){
  d.stop(function  (err) {
    console.log(err)
    process.exit()
  })
}else{
  d.restart(function (err) {
    console.log(err)
    // process.exit()
  })
}
