#!/bin/bash

set -e

add-init(){
	if [ -x "/etc/init.d/ma-agent" ]; then
	  update-rc.d ma-agent defaults >/dev/null 2>&1
	fi
}

add_system_user() {
	if ! getent passwd ma-agent >/dev/null; then
	    adduser --group --system --no-create-home ma-agent
	fi
}


case "$1" in
    configure)
        add-init
        add_system_user
        ;;
    abort-upgrade|abort-deconfigure|abort-remove)
        :
        ;;
    *)
        echo "Called with unknown argument $1, bailing out."
        exit 1
        ;;
esac